### PR TITLE
Adding search for movie 

### PR DESCRIPTION
**Pull request by Chrisdouce**
Hopefully creating a pull request to review the search feature.

### CODE REVIEW

**Comment by Chrisdouce** [comment]
I forgot to commit unit testing & e2e testing. Also, included some changes to the "No movies found" text.

**Review by Gulpiegator — CHANGES_REQUESTED** [review]
Line 14 and 15 should have the id after jinja

**Comment by TristinCMoore** [comment]
My previous change request was wrong. I mistook concatenation for jinja.

**Review by Gulpiegator — APPROVED** [review]
Looks good. Checked in git and the code looked good. Went ahead and pulled it and all the tests seemed to be running smoothly.

**Pull request merged**
